### ISSUE TITLE
Chat

### ISSUE THREAD

**Issue by Ariel-Berkowicz** [uilibrary/Octavia-admin-Pro-Issues#10]
You do not see the phone icon, attachment icon, and sending icon because it continues past the point of visibility.

**Comment by Ariel-Berkowicz** [comment]
https://octavia-admin.vercel.app/app/apps/chat

That page continues for forever, so you can't see the rest.  You can't see the mdi-phone on the right side.

**Comment by Ari-Berkowicz** [comment]
You can't see the mdi-phone on the right side.

**Comment by naime-hossain** [comment]
Thank you for report this issue, I will fix it and let you know :)

**Comment by naime-hossain** [comment]
The issue is fixed, will get the fixed code in the next update. thank you
