### ISSUE TITLE
Project operation problems

### ISSUE THREAD

**Issue by bwpows** [uilibrary/Octavia-admin-Pro-Issues#13]
I`ve recently bought your product and really love it.However, I came across a problem about project running. The details are shown in the picture below.
![1](https://user-images.githubusercontent.com/48264154/120258510-c6d29480-c2c4-11eb-8034-bb1db5f70b9f.png)

**Comment by naime-hossain** [comment]
> I`ve recently bought your product and really love it.However, I came across a problem about project running. The details are shown in the picture below.
> ![1](https://user-images.githubusercontent.com/48264154/120258510-c6d29480-c2c4-11eb-8034-bb1db5f70b9f.png)

Tha problem in main octavia source code or in starter-kit only ? thank you

**Comment by bwpows** [comment]
octavia source code and starter-kit are both have this problem.

**Comment by naime-hossain** [comment]
> octavia source code and starter-kit are both have this problem.

Thank you , May I know your Environment like, node version, npm etc . thank you

**Comment by bwpows** [comment]
Okay, in the picture below.
![image](https://user-images.githubusercontent.com/48264154/120432945-3ae86780-c3ad-11eb-9b43-e8463cca62c5.png)

**Comment by bwpows** [comment]
Can I refer to your environment? Thank you.

**Comment by bwpows** [comment]
Excuse me, is there a solution? waiting for your reply.

**Comment by naime-hossain** [comment]
> Excuse me, is there a solution? waiting for your reply.

Hello, I am running octavia in my two PC and working fine . can you please paste the error message here . thank you

**Comment by naime-hossain** [comment]
> I`ve recently bought your product and really love it.However, I came across a problem about project running. The details are shown in the picture below.
> ![1](https://user-images.githubusercontent.com/48264154/120258510-c6d29480-c2c4-11eb-8034-bb1db5f70b9f.png)

in this image, I see the code compiled successfully, when this error occurred?

**Comment by naime-hossain** [comment]
> Okay, in the picture below.
> ![image](https://user-images.githubusercontent.com/48264154/120432945-3ae86780-c3ad-11eb-9b43-e8463cca62c5.png)

can you please try with the updated node version and let me know. thank you

**Comment by bwpows** [comment]
Solved, it may be a node version problem. Thank you.

**Comment by naime-hossain** [comment]
> Solved, it may be a node version problem. Thank you.

Great , Thank you
