### ISSUE TITLE
[Enhancement] Improve the shape of the "my profile" pill menu

### ISSUE THREAD

**Issue by Turbine1991** [uilibrary/Octavia-admin-Pro-Issues#16]
![image](https://user-images.githubusercontent.com/7228980/123247718-4a397b80-d53b-11eb-90c8-c83870ac7b3a.png)

Edit `layouts/vertical-white/AppBar.vue`

Replace:
`<v-chip pill class="transparent py-5"`
to
`<v-chip pill class="transparent rounded-pill py-6"`

**Comment by naime-hossain** [comment]
fixed
