### ISSUE TITLE
Sign up page is missing

### ISSUE THREAD

**Issue by Ari-Berkowicz** [uilibrary/Octavia-admin-Pro-Issues#2]
https://cdn.discordapp.com/attachments/830537676629213244/830661389471318056/Capture.PNG

**Comment by naime-hossain** [comment]
Fixed the issue 
![image](https://user-images.githubusercontent.com/12586039/114297859-ede6c400-9ad4-11eb-819d-4e0bd5ff05ab.png)
in this file src\views\app\sessions\SignInTwo.vue
There was a typo in signup page link 
The correct link is : https://octavia-admin.vercel.app/app/sessions/sign-up-2
