### ISSUE TITLE
Unpin the sidebar

### ISSUE THREAD

**Issue by Ari-Berkowicz** [uilibrary/Octavia-admin-Pro-Issues#3]
This happens when I unpin first the sidebar and then switch to the section option.

https://cdn.discordapp.com/attachments/830537676629213244/830661592693473321/Capture.PNG

**Comment by Ariel-Berkowicz** [comment]
I just checked on the latest update. It has not been fixed yet.

**Comment by naime-hossain** [comment]
I will fix this soon , don't  worry :) will update you when I fix this. thank you

**Comment by naime-hossain** [comment]
Hello,  @Ari-Berkowicz  this issue is fixed and you will get the solution in Octavia-1.7.1, which will be updated in-store soon. Please check the demo and let me know if this issue is resolved or not. thank you
