### ISSUE TITLE
Vue 2 version included?

### ISSUE THREAD

**Issue by nicolaskopp** [uilibrary/Octavia-admin-Pro-Issues#37]
We are at vue 2.7 at the moment (& vuetify 2.6), we cannot upgrade to vue 3 for the time being, is the vue 2 version also included when we buy the theme?

Thank you very much for replying.

**Comment by nicolaskopp** [comment]
@naime-hossain ?

**Comment by naime-hossain** [comment]
Yes vue 2 version included

**Comment by nicolaskopp** [comment]
solved - vue 2 version is included in package.
