### ISSUE TITLE
Octavia 1.4.1 installation bug with vuetify

### ISSUE THREAD

**Issue by Ari-Berkowicz** [uilibrary/Octavia-admin-Pro-Issues#8]
This selector doesn't have any properties and won't be rendered.
   ╷
16 │   .v-calendar-daily_head-day
   │   ^^^^^^^^^^^^^^^^^^^^^^^^^^
   ╵

98% after emitting CopyPlugin

 ERROR  Failed to compile with 3 errors
 error  in ./node_modules/vuetify/src/components/VSelect/VSelect.sass

Syntax Error: SassError: Expected identifier.
   ╷
68 │       position: relative
   │                         ^
   ╵
  node_modules\vuetify\src\components\VSelect\VSelect.sass 68:25  root stylesheet

 @ ./node_modules/vuetify/src/components/VSelect/VSelect.sass 4:14-206 15:3-20:5 16:22-214
 @ ./node_modules/vuetify/lib/components/VSelect/VSelect.js
 @ ./node_modules/vuetify/lib/components/VSelect/index.js
 @ ./src/views/app/forms/Selects.vue
 @ ./src/router/index.js
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://192.168.1.191:8082&sockPath=/sockjs-node (webpack)/hot/dev-server.js ./s

 error  in ./node_modules/vuetify/src/components/VWindow/VWindow.sass

Syntax Error: SassError: Expected identifier.
  ╷
4 │   overflow: hidden
  │                   ^
  ╵
  node_modules\vuetify\src\components\VWindow\VWindow.sass 4:19  root stylesheet

 @ ./node_modules/vuetify/src/components/VWindow/VWindow.sass 4:14-206 15:3-20:5 16:22-214
 @ ./node_modules/vuetify/lib/components/VWindow/VWindow.js
 @ ./node_modules/vuetify/lib/components/VWindow/index.js
 @ ./node_modules/vuetify/lib/components/index.js
 @ ./node_modules/vuetify/lib/index.js
 @ ./src/plugins/vuetify.js
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://192.168.1.191:8082&sockPath=/sockjs-node (webpack)/hot/dev-server.js ./s

 error  in ./node_modules/vuetify/src/components/VCalendar/VCalendarCategory.sass

Syntax Error: SassError: expected ":".
   ╷
   │                                   ^
   ╵
  node_modules\vuetify\src\components\VCalendar\VCalendarCategory.sass 13:35  root stylesheet

 @ ./node_modules/vuetify/src/components/VCalendar/VCalendarCategory.sass 4:14-216 15:3-20:5 16:22-224
 @ ./node_modules/vuetify/lib/components/VCalendar/VCalendarCategory.js
 @ ./node_modules/vuetify/lib/components/VCalendar/index.js
 @ ./node_modules/vuetify/lib/components/index.js
 @ ./node_modules/vuetify/lib/index.js
 @ ./src/plugins/vuetify.js
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://192.168.1.191:8082&sockPath=/sockjs-node (webpack)/hot/dev-server.js ./src/main.js

**Comment by naime-hossain** [comment]
Working on it , will fix this issue soon and update

**Comment by naime-hossain** [comment]
Issue fix with Octavia-1.5.0 version Now but it works only with the Lock file (Temporary fix) Need to find a way to work without lock file.

**Comment by naime-hossain** [comment]
After 6 hours of Trail and error, at last, I am able to fix the issue, now Octavia will works without default lock, You will get this in next update, Octavia-2.0.0 Version. will release this within few days :) 
The Problem was in the Vuetify Version actually.
Thank you for finding this issue.

**Comment by naime-hossain** [comment]
Bro, I was looking for the solution for the last 12 hours and there is no single trace of it, and then I tried Vuetify  free zero themes and without lock file, this also throws the same error, so I think the problem is not with my theme, actually its vuetify issue 
![image](https://user-images.githubusercontent.com/12586039/115154574-60d7d800-a09d-11eb-82dc-6b83c7c8c680.png)
Its Really Strange issue 
will try to find a work around for it, in the future, and for now, we have to use the lock file and I will add the lock file with the next theme updates. Thank you

**Comment by Ariel-Berkowicz** [comment]
It has been fixed
