### ISSUE TITLE
Where could I find the release note of v1.6?

### ISSUE THREAD

**Issue by ferrywlto** [uilibrary/Octavia-admin-Pro-Issues#9]
Hi, just glad to know a new version released.

I can see that the zip file size dropped from 57.7MB (v1.2) to 6.6MB (v1.6), may I know what have changed in the new version? Thank you.

**Comment by naime-hossain** [comment]
I Removed unused files/images and optimize images and fix some minor issue not a major update, I will create a release note here today for  Octavia-1.6.0 Thank you

**Comment by naime-hossain** [comment]
Release note added : 

1. ->Packages Update
2. ->Fix Some Issue after Package Update
3. ->Yarn Issue fix, Now Yarn and Npm both will work
4. ->File size decrease from 56MB to 6MB
5. -> remove unwanted file and images
6. ->Signup Page link fix
7. ->Sidebar font size Update
8. ->Utility class issue fix for flex-grow
